blank_issues_enabled: true
contact_links:
  - name: Community Discussion & Questions
    url: https://github.com/stevene1919/hisense_vidaa/discussions
    about: Ask questions, share tips, or discuss ideas with the community.
