name: Lint & Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hassfest:
    name: Run Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare directory structure for Hassfest
        run: |
          mkdir -p custom_components/hisense_vidaa
          find . -maxdepth 1 -not -name '.' -not -name '..' -not -name 'custom_components' -not -name '.git' -not -name '.github' -exec mv {} custom_components/hisense_vidaa/ \;

      - name: Home Assistant Hassfest Validation
        uses: home-assistant/actions/hassfest@master

  ruff:
    name: Run Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
