name: Lint & Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hassfest:
    name: Run Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Home Assistant Hassfest Validation
        uses: home-assistant/actions/hassfest@master

  ruff:
    name: Run Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
